# Generated by Django 4.2.30 on 2026-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamTopSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(db_index=True)),
                ('current_players', models.IntegerField(default=0)),
                ('peak_players', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['appid', 'timestamp'], name='games_steam_appid_4f8226_idx')],
            },
        ),
    ]
